---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zhaz4965/public_html/Quran-Digital-PHP/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp detail.php $DEPLOYPATH
    - /bin/cp koneksi.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
